/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketplaceSol from "./Marketplace.sol";
export type { marketplaceSol };
export type { GiftNFT } from "./GiftNFT";
export type { RedemptionTracker } from "./RedemptionTracker";
